name: Deploy Devops
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: build artifact
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Format
      run: npm run format
    - name: Eslint
      run: npm run lint
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: build
        path: build

  publish_artifact:
    needs: [ build ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3.5.1
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - uses: actions/download-artifact@v3.0.1
      with:
        name: build
        path: build
    - name: Pakage the build
      run: |
        cd build
        listaArchivos=`ls`
        zip -r ../devops.zip $listaArchivos
    - name: Copy the build to the EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ SECRETS_HOST_DEVOPS }}
        username: ${{ SECRETS_USERNAME_DEVOPS }}
        key_path: "devops/id_rsa"
        source: "devops.zip"
        target: "/home/softitlan/projects/artifacts/devops"
  deploy:
    needs: [ publish_artifact ]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Deploy artifact
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ SECRETS_HOST_DEVOPS }}
        username: ${{ SECRETS_USERNAME_DEVOPS  }}
        key_path: "devops/id_rsa"
        script: |
          cd /home/softitlan/projects/artifacts/devops
          mv devops.zip /var/www/html/devops
          cd /var/www/html/devops
          unzip -o devops.zip
          rm devops.zip